extends:
  - google
globals:
  React: true
env:
  browser: true
  commonjs: true
  es6: true
  node: true
parserOptions:
  ecmaVersion: 6
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
parser: babel-eslint
rules:
  jsx-uses-vars: 0
  no-unused-vars: 0
  no-console:
    - error
    - allow:
      - warn
      - error
      - info
